### ISSUE TITLE
Inconsistencies between os and pathlib libraries 

### ISSUE THREAD

**Issue by Emvlt** [CambridgeCIA/AItomotools#2]
Some files use os whilst others use pathlib. Would it be good to agree on one format (I vote for pathlib) and stick to it?

Don't mind doing the reformatting :)

**Comment by AnderBiguri** [comment]
@Emvlt sure!

Yeah, this is for now just my old crappy code being a bit cleaned up, so none of it is set in stone. If you have a better/cleaner way, do make a PR!

**Comment by AnderBiguri** [comment]
maybe fixed already? From now on lets use pathlib.
